name: "GitHub Actions Weather Bot"

on:
  push:
  schedule:
    - cron: "0 21 * * *"

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v1
      - name: "Get Result"
        run: bash ./weather.sh
      - name: "Send mail"
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 成都天气预报
          body: file://result.png
          to: joey2019q@163.com
          from: 阿飞
          content_type: image/png